version: "3"

services:

  database:
    image: postgres

    ports:
      - 5432:5432

    container_name: ngv_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: valente
    
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"